"""empty message

Revision ID: e7554a6c9379
Revises: 8ae63ab044e4
Create Date: 2022-08-23 01:10:07.142361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7554a6c9379'
down_revision = '8ae63ab044e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist-items')
    op.drop_table('venue-items')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venue-items',
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['show_id'], ['Show.id'], name='venue-items_show_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], name='venue-items_venue_id_fkey'),
    sa.PrimaryKeyConstraint('venue_id', 'show_id', name='venue-items_pkey')
    )
    op.create_table('artist-items',
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='artist-items_artist_id_fkey'),
    sa.ForeignKeyConstraint(['show_id'], ['Show.id'], name='artist-items_show_id_fkey'),
    sa.PrimaryKeyConstraint('artist_id', 'show_id', name='artist-items_pkey')
    )
    # ### end Alembic commands ###
